//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finances.Persistence.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BalanceDate
    {
        public BalanceDate()
        {
            this.BalanceDateBankAccounts = new HashSet<BalanceDateBankAccount>();
        }
    
        public int BalanceDateId { get; set; }
        public System.DateTime DateOfBalance { get; set; }
        public System.DateTime RecordCreatedDateTime { get; set; }
    
        public virtual ICollection<BalanceDateBankAccount> BalanceDateBankAccounts { get; set; }
    }
}
