//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finances.Persistence.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BalanceDateBankAccount
    {
        public int BalanceDateBankAccountId { get; set; }
        public int BalanceDateId { get; set; }
        public int BankAccountId { get; set; }
        public decimal BalanceAmount { get; set; }
        public System.DateTime RecordCreatedDateTime { get; set; }
    
        public virtual BalanceDate BalanceDate { get; set; }
        public virtual BankAccount BankAccount { get; set; }
    }
}
