//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finances.Persistence.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cashflow
    {
        public Cashflow()
        {
            this.CashflowBankAccounts = new HashSet<CashflowBankAccount>();
        }
    
        public int CashflowId { get; set; }
        public string Name { get; set; }
        public decimal OpeningBalance { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime RecordCreatedDateTime { get; set; }
        public System.DateTime RecordUpdatedDateTime { get; set; }
    
        public virtual ICollection<CashflowBankAccount> CashflowBankAccounts { get; set; }
    }
}
