//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finances.Persistence.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class FinanceEntities : DbContext
    {
        public FinanceEntities(string nameOrConnectionString="name=FinanceEntities")
            : base(nameOrConnectionString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Bank> Banks { get; set; }
        public DbSet<BankAccount> BankAccounts { get; set; }
        public DbSet<Cashflow> Cashflows { get; set; }
        public DbSet<CashflowBankAccount> CashflowBankAccounts { get; set; }
        public DbSet<Transfer> Transfers { get; set; }
        public DbSet<TransferCategory> TransferCategories { get; set; }
        public DbSet<BalanceDate> BalanceDates { get; set; }
        public DbSet<BalanceDateBankAccount> BalanceDateBankAccounts { get; set; }
    
        public virtual ObjectResult<GetDataTest_Result> GetDataTest()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDataTest_Result>("GetDataTest");
        }
    }
}
