//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finances.Persistence.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer
    {
        public int TransferId { get; set; }
        public string Name { get; set; }
        public Nullable<int> FromBankAccountId { get; set; }
        public Nullable<int> ToBankAccountId { get; set; }
        public int TransferCategoryId { get; set; }
        public decimal Amount { get; set; }
        public decimal AmountTolerence { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Frequency { get; set; }
        public bool IsEnabled { get; set; }
        public System.DateTime RecordCreatedDateTime { get; set; }
        public System.DateTime RecordUpdatedDateTime { get; set; }
        public int FrequencyDays { get; set; }
    
        public virtual BankAccount FromBankAccount { get; set; }
        public virtual BankAccount ToBankAccount { get; set; }
        public virtual TransferCategory TransferCategory { get; set; }
    }
}
