IF OBJECT_ID('dbo.Bank') IS NULL
BEGIN
	CREATE TABLE dbo.Bank
	(
		BankId  INT IDENTITY(1,1) NOT NULL
		,Name   VARCHAR(100)
		,Logo   VARBINARY(MAX)
		,CONSTRAINT PK_Bank PRIMARY KEY CLUSTERED (BankId ASC)
		,CONSTRAINT UK_Bank_Name UNIQUE (Name)
	)
END
GO
